CREATE DATABASE EMPLOYEE_MANAGEMENT_DB
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

USE EMPLOYEE_MANAGEMENT_DB;

	CREATE TABLE DEPARTMENTS (
		DEPARTMENT_ID INT auto_increment,
		DEPARTMENT_NAME VARCHAR(100) NOT NULL,
		LOCATION VARCHAR(150),
		CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
		
		PRIMARY KEY (DEPARTMENT_ID)
	);

	CREATE TABLE EMPLOYEES (
		EMPLOYEE_ID INT auto_increment,
		FIRST_NAME VARCHAR(100) NOT NULL,
		LAST_NAME VARCHAR(100) NOT NULL,
		EMAIL VARCHAR(100) UNIQUE NOT NULL,
		PHONE_NUMBER VARCHAR(100) NOT NULL,
		HIRE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
		JOB_TITLE VARCHAR(100) NOT NULL,
		SALARY INT NOT NULL,
		DEPARTMENT_ID INT,
		MANAGER_ID INT,
		STATUS TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1: active, 0: inactive',
		CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
		MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
		
		-- PRIMARY KEY
		PRIMARY KEY (EMPLOYEE_ID),
		
		-- CHECK SALARY CONSTRAINT
		CHECK (SALARY >= 1000 AND SALARY < 999999),
		-- Khai bao FK DEPARTMENT_ID
		CONSTRAINT FK_DEPARTMENT
		FOREIGN KEY (DEPARTMENT_ID)
		REFERENCES DEPARTMENTS(DEPARTMENT_ID)
		ON DELETE CASCADE -- IF YOU DELETE DEPARTMENT, YOU DELETE EMPLOYEE BELONG TO DEPARTMENT
		ON UPDATE CASCADE, -- IF DEPARTMENT_ID OF DEPARTMENT TABLE CHANGE, FK DEPARTMENT_ID IN THIS CHANGE TOO
		
		-- KHAI BAO FK MANAGER_ID
		CONSTRAINT FK_MANAGER_EMPLOYEE
		FOREIGN KEY (MANAGER_ID)
		REFERENCES EMPLOYEES(EMPLOYEE_ID)
		ON DELETE SET NULL -- IF YOU DELETE RECORD DAD, FK IN RECORD SUB BEING SET TO NULL
	);