globalError = Internal System Error

error.database=Database Error

error.employee.firstName.required = First Name is required <br />
error.employee.lastName.required  = Last Name is required <br />
error.employee.email.required     = Email is required <br />
error.employee.phoneNumber.required = Phone Number is required <br />
error.employee.jobTitle.required = Job Title is required <br />
error.employee.salary.required    = Salary must be between 1,000 and 999,999 <br />
